### PR TITLE
Machine translation errors

### PR DESCRIPTION
**Pull request by krejcar25**
GitHub marked the whole thing as changed, only changes made on line 46

### CODE REVIEW

**Comment by mairaw** [comment]
@krejcar25 I need to follow up with GitHub to see if this is expected. It happens to all translated content files.

**Comment by svick** [comment]
> GitHub marked the whole thing as changed, only changes made on line 46

As far as I can tell, that's because the original document contains a mix of Unix- and Windows-style line endings (`\n` and `\r\n`, respectively), but your PR changes them to consistently use the Windows style.

@mairaw Maybe the machine translation-produced files should use consistent line endings? That would probably require changing whatever process is producing them.

**Comment by krejcar25** [comment]
@svick The fact that Microsoft themselves produced code that can't decide between Unix and Windows line ends is mildly infuriating, isn't it?

**Comment by gosali** [comment]
Hi @krejcar25 , we are still in discussing, will update the decision later soon. 
  
Thanks for your support,
Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
@krejcar25 , Thank you for your feedback and suggestion! 

The suggestion will be merged to the production, we will re-release this articles in the next loc release round.

Microsoft C&E Localization Team

**Pull request merged**
